aws:
- account_id: '78567'
  account_name: jhghj
  regions:
  - us-east-1
  type: account
- account_id: '7567'
  account_name: jgkh
  regions:
  - us-east-1
  type: org
- account_id: '87567'
  account_name: cghj
  regions:
  - us-east-1
  type: account
- account_id: '678678'
  account_name: bhjv
  regions:
  - us-east-1
  type: org
- account_id: '54265'
  account_name: gfd
  regions:
  - us-east-1
  type: account
- account_id: '54254'
  account_name: gfe
  regions:
  - us-east-1
  type: org
- account_id: '3243'
  account_name: dew
  regions:
  - us-east-1
  type: account
- account_id: '43242'
  account_name: dsd
  regions:
  - us-east-1
  type: org
