aws:
- account_id: t654765
  account_name: hgfdhgfd
  regions:
  - us-east-1
  type: account
- account_id: '7899879867'
  account_name: hgfmhfgm
  regions:
  - us-east-1
  type: org
- account_id: '654365236'
  account_name: hgfdhgdf
  regions:
  - us-east-1
  type: org
- account_id: '7654765'
  account_name: jhgj
  regions:
  - us-east-1
  type: account
- account_id: 097878733
  account_name: kgjhkjhg
  regions:
  - us-east-1
  type: account
- account_id: '65432654'
  account_name: gfvdbgf
  regions:
  - us-east-1
  type: account
