aws:
- account_id: '7895635'
  account_name: gdfyujk
  regions:
  - us-east-1
  type: org
- account_id: '78567465'
  account_name: bjkghjhkj
  regions:
  - us-east-1
  type: org
- account_id: '65436534'
  account_name: gfsdhgfd
  regions:
  - us-east-1
  type: account
