aws:
- account_id: '78567'
  account_name: jhghj
  regions:
  - us-east-1
  type: account
- account_id: '7567'
  account_name: jgkh
  regions:
  - us-east-1
  type: org
- account_id: '87567'
  account_name: cghj
  regions:
  - us-east-1
  type: account
